name: test
on:
  push:
    branches: [ main ]
jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Set up Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - run: npm install

      - name: "run npm schedule"
        run: echo ${{ secrets.TWITTER_CONSUMER_KEY }}
      
      - run: echo "hi"
